### ISSUE TITLE
[iOS] local video is horizontally flipped

### ISSUE THREAD

**Issue by miguelsanchez** [pexip/pexkit-sdk#46] opened 2016-08-26 14:17 UTC
On iOS the local video representation (Conference.videoSelfView) when using the front camera is mirrored. If compared to others platforms (Hangout, FaceTime) or PexKit Android SDK, the local representation is flipped horizontally.

Just to clarify, the video that gets transmitted is ok, it's just the local representation of it.

For now I can use a workaround for this case a apply a transform to be able to offer a similar experience as other platforms do, but it should be the default behavior:
  
    selfVideoView.transform = CGAffineTransformMakeScale(-1.0, 1.0)

**Comment by jfowens** [comment] 2016-08-26 14:19
@miguelsanchez: this is expected and desired behavior associated with the iOS SDK. We purposefully choose to mirror the video in local selfview knowing that any who would like to adjust it can do so as you have within your app. 

I'll close this as not a bug, but certainly appreciate the feedback.

**Closed by jfowens** 2016-08-26 14:19 UTC

**Comment by miguelsanchez** [comment] 2016-08-26 14:22
Thanks. If that's the reason I find confusing that the Android and the iOS SDKs behave differently for this particular case.

**Comment by jfowens** [comment] 2016-08-26 14:23
Your point is certainly a fair one. I personally agree that the two apps should normalize behavior and will work with the development team to do this as we continue to advance the apps.
